#!/usr/bin/env bash
# the script stops apache2 and start nginx as web service under user nginx
systemctl is-active --quiet apache2 && systemctl stop apache2

# Start Nginx with custom configuration
echo "user nginx;worker_processes 4;events {worker_connections 1024;} http {server {listen 8080;}}" | sudo -u nginx nginx -g "daemon off;"
